version: '3.8'
services:
  # https://hub.docker.com/_/cassandra/
  cassandra:
    image: cassandra:3
    restart: unless-stopped
    container_name: cassandra
    ports:
      - 7000:7000
      - 9042:9042
    environment:
      - JVM_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Xms512m -Xmx1024m
    volumes:
      - cassandra-volume:/var/lib/cassandra

  # https://hub.docker.com/r/brunocesar/glowroot-central/
  glowroot:
    image: brunocesar/glowroot-central:0.13.6
    container_name: glowroot
    restart: unless-stopped
    depends_on:
      - cassandra
    ports:
      - 4000:4000
      - 8181:8181
    environment:
      - CASSANDRA_CONTACT_POINTS=cassandra
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_SYMMETRIC_ENCRYPTION_KEY=9f8b7e86573ea0bf0c1ab43fd7b0d341

  # https://hub.docker.com/_/postgres
  postgres:
    image: postgres:11.6
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql-volume:/var/lib/postgresql/data

volumes:
  cassandra-volume:
  postgresql-volume:
